;exLIB.package('arduino.device', function(pack){
	var dev = pack.Device('mega', 'Arduino Mega Board').Category('Arduino')
	dev.Provide('type:core.type.int', 'type:core.type.string')
	
	dev.Function('setup');
	dev.Function('loop');
	
	dev.Component('serial').Label('Serial Port').Require('component:di0', 'component:di1', 'component:do0', 'component:do1');
	dev.Component('serial1').Label('Serial Port 1').Require('component:di19', 'component:do19', 'component:di18', 'component:do18');
	dev.Component('serial2').Label('Serial Port 2').Require('component:di16', 'component:di17', 'component:do16', 'component:do17');
	dev.Component('serial3').Label('Serial Port 3').Require('component:di14', 'component:di15', 'component:do14', 'component:do15');
	
	dev.Component('di0', 'Digital Input D0').Require('component:do0');
	dev.Component('di1', 'Digital Input D1').Require('component:do1');
	dev.Component('di2', 'Digital Input D2').Require('component:do2');
	dev.Component('di3', 'Digital Input D3').Require('component:do3');
	dev.Component('di4', 'Digital Input D4').Require('component:do4');
	dev.Component('di5', 'Digital Input D5').Require('component:do5');
	dev.Component('di6', 'Digital Input D6').Require('component:do6');
	dev.Component('di7', 'Digital Input D7').Require('component:do7');
	dev.Component('di8', 'Digital Input D8').Require('component:do8');
	dev.Component('di9', 'Digital Input D9').Require('component:do9');
	dev.Component('di10', 'Digital Input D10').Require('component:do10');
	dev.Component('di11', 'Digital Input D11').Require('component:do11');
	dev.Component('di12', 'Digital Input D12').Require('component:do12');
	dev.Component('di13', 'Digital Input D13').Require('component:do13');
	dev.Component('di14', 'Digital Input D14').Require('component:do14');
	dev.Component('di15', 'Digital Input D15').Require('component:do15');
	dev.Component('di16', 'Digital Input D16').Require('component:do16');
	dev.Component('di17', 'Digital Input D17').Require('component:do17');
	dev.Component('di18', 'Digital Input D18').Require('component:do18');
	dev.Component('di19', 'Digital Input D19').Require('component:do19');
	dev.Component('di20', 'Digital Input D20').Require('component:do20');
	dev.Component('di21', 'Digital Input D21').Require('component:do21');
	dev.Component('di22', 'Digital Input D22').Require('component:do22');
	dev.Component('di23', 'Digital Input D23').Require('component:do23');
	dev.Component('di24', 'Digital Input D24').Require('component:do24');
	dev.Component('di25', 'Digital Input D25').Require('component:do25');
	dev.Component('di26', 'Digital Input D26').Require('component:do26');
	dev.Component('di27', 'Digital Input D27').Require('component:do27');
	dev.Component('di28', 'Digital Input D28').Require('component:do28');
	dev.Component('di29', 'Digital Input D29').Require('component:do29');
	dev.Component('di30', 'Digital Input D30').Require('component:do30');
	dev.Component('di31', 'Digital Input D31').Require('component:do31');
	dev.Component('di32', 'Digital Input D32').Require('component:do32');
	dev.Component('di33', 'Digital Input D33').Require('component:do33');
	dev.Component('di34', 'Digital Input D34').Require('component:do34');
	dev.Component('di35', 'Digital Input D35').Require('component:do35');
	dev.Component('di36', 'Digital Input D36').Require('component:do36');
	dev.Component('di37', 'Digital Input D37').Require('component:do37');
	dev.Component('di38', 'Digital Input D38').Require('component:do38');
	dev.Component('di39', 'Digital Input D39').Require('component:do39');
	dev.Component('di40', 'Digital Input D40').Require('component:do40');
	dev.Component('di41', 'Digital Input D41').Require('component:do41');
	dev.Component('di42', 'Digital Input D42').Require('component:do42');
	dev.Component('di43', 'Digital Input D43').Require('component:do43');
	dev.Component('di44', 'Digital Input D44').Require('component:do44');
	dev.Component('di45', 'Digital Input D45').Require('component:do45');
	dev.Component('di46', 'Digital Input D46').Require('component:do46');
	dev.Component('di47', 'Digital Input D47').Require('component:do47');
	dev.Component('di48', 'Digital Input D48').Require('component:do48');
	dev.Component('di49', 'Digital Input D49').Require('component:do49');
	dev.Component('di50', 'Digital Input D50').Require('component:do50');
	dev.Component('di51', 'Digital Input D51').Require('component:do51');
	dev.Component('di52', 'Digital Input D52').Require('component:do52');
	dev.Component('di53', 'Digital Input D53').Require('component:do53');

	dev.Component('do0', 'Digital Output D0').Require('component:di0');
	dev.Component('do1', 'Digital Output D1').Require('component:di1');
	dev.Component('do2', 'Digital Output D2').Require('component:di2');
	dev.Component('do3', 'Digital Output D3').Require('component:di3');
	dev.Component('do4', 'Digital Output D4').Require('component:di4');
	dev.Component('do5', 'Digital Output D5').Require('component:di5');
	dev.Component('do6', 'Digital Output D6').Require('component:di6');
	dev.Component('do7', 'Digital Output D7').Require('component:di7');
	dev.Component('do8', 'Digital Output D8').Require('component:di8');
	dev.Component('do9', 'Digital Output D9').Require('component:di9');
	dev.Component('do10', 'Digital Output D10').Require('component:di10');
	dev.Component('do11', 'Digital Output D11').Require('component:di11');
	dev.Component('do12', 'Digital Output D12').Require('component:di12');
	dev.Component('do13', 'Digital Output D13').Require('component:di13');
	dev.Component('do14', 'Digital Output D14').Require('component:di14');
	dev.Component('do15', 'Digital Output D15').Require('component:di15');
	dev.Component('do16', 'Digital Output D16').Require('component:di16');
	dev.Component('do17', 'Digital Output D17').Require('component:di17');
	dev.Component('do18', 'Digital Output D18').Require('component:di18');
	dev.Component('do19', 'Digital Output D19').Require('component:di19');
	dev.Component('do20', 'Digital Output D20').Require('component:di20');
	dev.Component('do21', 'Digital Output D21').Require('component:di21');
	dev.Component('do22', 'Digital Output D22').Require('component:di22');
	dev.Component('do23', 'Digital Output D23').Require('component:di23');
	dev.Component('do24', 'Digital Output D24').Require('component:di24');
	dev.Component('do25', 'Digital Output D25').Require('component:di25');
	dev.Component('do26', 'Digital Output D26').Require('component:di26');
	dev.Component('do27', 'Digital Output D27').Require('component:di27');
	dev.Component('do28', 'Digital Output D28').Require('component:di28');
	dev.Component('do29', 'Digital Output D29').Require('component:di29');
	dev.Component('do30', 'Digital Output D30').Require('component:di30');
	dev.Component('do31', 'Digital Output D31').Require('component:di31');
	dev.Component('do32', 'Digital Output D32').Require('component:di32');
	dev.Component('do33', 'Digital Output D33').Require('component:di33');
	dev.Component('do34', 'Digital Output D34').Require('component:di34');
	dev.Component('do35', 'Digital Output D35').Require('component:di35');
	dev.Component('do36', 'Digital Output D36').Require('component:di36');
	dev.Component('do37', 'Digital Output D37').Require('component:di37');
	dev.Component('do38', 'Digital Output D38').Require('component:di38');
	dev.Component('do39', 'Digital Output D39').Require('component:di39');
	dev.Component('do40', 'Digital Output D40').Require('component:di40');
	dev.Component('do41', 'Digital Output D41').Require('component:di41');
	dev.Component('do42', 'Digital Output D42').Require('component:di42');
	dev.Component('do43', 'Digital Output D43').Require('component:di43');
	dev.Component('do44', 'Digital Output D44').Require('component:di44');
	dev.Component('do45', 'Digital Output D45').Require('component:di45');
	dev.Component('do46', 'Digital Output D46').Require('component:di46');
	dev.Component('do47', 'Digital Output D47').Require('component:di47');
	dev.Component('do48', 'Digital Output D48').Require('component:di48');
	dev.Component('do49', 'Digital Output D49').Require('component:di49');
	dev.Component('do50', 'Digital Output D50').Require('component:di50');
	dev.Component('do51', 'Digital Output D51').Require('component:di51');
	dev.Component('do52', 'Digital Output D52').Require('component:di52');
	dev.Component('do53', 'Digital Output D53').Require('component:di53');
	
	
	dev.Component('a0', 'Analog Input A0');
	dev.Component('a1', 'Analog Input A1');
	dev.Component('a2', 'Analog Input A2');
	dev.Component('a3', 'Analog Input A3');
	dev.Component('a4', 'Analog Input A4');
	dev.Component('a5', 'Analog Input A5');
	dev.Component('a6', 'Analog Input A6');
	dev.Component('a7', 'Analog Input A7');
	dev.Component('a8', 'Analog Input A8');
	dev.Component('a9', 'Analog Input A9');
	dev.Component('a10', 'Analog Input A10');
	dev.Component('a11', 'Analog Input A11');
	dev.Component('a12', 'Analog Input A12');
	dev.Component('a13', 'Analog Input A13');
	dev.Component('a14', 'Analog Input A14');
	dev.Component('a15', 'Analog Input A15');

	dev.Component('pwm2', 'PWM Output on D2').Require('component:di2', 'component:do2');
	dev.Component('pwm3', 'PWM Output on D3').Require('component:di3', 'component:do3');
	dev.Component('pwm4', 'PWM Output on D4').Require('component:di4', 'component:do4');
	dev.Component('pwm5', 'PWM Output on D5').Require('component:di5', 'component:do5');
	dev.Component('pwm6', 'PWM Output on D6').Require('component:di6', 'component:do6');
	dev.Component('pwm7', 'PWM Output on D7').Require('component:di7', 'component:do7');
	dev.Component('pwm8', 'PWM Output on D8').Require('component:di8', 'component:do8');
	dev.Component('pwm9', 'PWM Output on D9').Require('component:di9', 'component:do9');
	dev.Component('pwm10', 'PWM Output on D10').Require('component:di10', 'component:do10');
	dev.Component('pwm11', 'PWM Output on D11').Require('component:di11', 'component:do11');
	dev.Component('pwm12', 'PWM Output on D12').Require('component:di12', 'component:do12');
	dev.Component('pwm13', 'PWM Output on D13').Require('component:di13', 'component:do13');
	dev.Component('pwm44', 'PWM Output on D44').Require('component:di44', 'component:do44');
	dev.Component('pwm45', 'PWM Output on D45').Require('component:di45', 'component:do45');
	dev.Component('pwm46', 'PWM Output on D46').Require('component:di46', 'component:do46');

	
	dev.Component('spi0').Label('SPI Port').Require('component:di50', 'component:do50', 'component:di51', 'component:do51', 'component:di52', 'component:do52');
	
	dev.Component('twi0').Label('TWI Port').Require('component:di20', 'component:do20', 'component:di21', 'component:do21');

	
	dev.Component('component:i2c').Label('I²c Port').Require('component:a4').Require('component:a5');
});
